//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyKhoEntities : DbContext
    {
        public QuanLyKhoEntities()
            : base("name=QuanLyKhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kho_Chua> Kho_Chua { get; set; }
        public virtual DbSet<Loai_SP> Loai_SP { get; set; }
        public virtual DbSet<Nha_Cung_Cap> Nha_Cung_Cap { get; set; }
        public virtual DbSet<Phieu_Nhap_Hang_Hoa> Phieu_Nhap_Hang_Hoa { get; set; }
        public virtual DbSet<Phieu_Xuat_Kho_Chua> Phieu_Xuat_Kho_Chua { get; set; }
        public virtual DbSet<Table_Role> Table_Role { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Phieu_Nhap> Phieu_Nhap { get; set; }
        public virtual DbSet<Phieu_Xuat> Phieu_Xuat { get; set; }
        public virtual DbSet<Hang_Hoa> Hang_Hoa { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
    
        public virtual ObjectResult<sp_Ma_Phieu_Gan_Nhat_Result> sp_Ma_Phieu_Gan_Nhat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Ma_Phieu_Gan_Nhat_Result>("sp_Ma_Phieu_Gan_Nhat");
        }
    
        public virtual int sp_UpdateTongTien(Nullable<int> ma_phieu, Nullable<decimal> tong_tien)
        {
            var ma_phieuParameter = ma_phieu.HasValue ?
                new ObjectParameter("ma_phieu", ma_phieu) :
                new ObjectParameter("ma_phieu", typeof(int));
    
            var tong_tienParameter = tong_tien.HasValue ?
                new ObjectParameter("tong_tien", tong_tien) :
                new ObjectParameter("tong_tien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateTongTien", ma_phieuParameter, tong_tienParameter);
        }
    }
}
