//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieu_Xuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phieu_Xuat()
        {
            this.Phieu_Xuat_Kho_Chua = new HashSet<Phieu_Xuat_Kho_Chua>();
        }
    
        public int Phieu_Xuat_Id { get; set; }
        public Nullable<decimal> Tong_Tien { get; set; }
        public Nullable<System.DateTime> Ngay_Xuat { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieu_Xuat_Kho_Chua> Phieu_Xuat_Kho_Chua { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
