//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Models.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieu_Xuat_Kho_Chua
    {
        public int Hang_Hoa_Id { get; set; }
        public int Phieu_Xuat_Id { get; set; }
        public Nullable<decimal> Don_Gia { get; set; }
        public Nullable<int> So_Luong { get; set; }
    
        public virtual Kho_Chua Kho_Chua { get; set; }
        public virtual Phieu_Xuat Phieu_Xuat { get; set; }
    }
}
